- hosts: workstation
  gather_facts: true
  roles:
    - name: osp-facts

- name: gather fact for dbs apps and load-balancers
  hosts: appdbs:apps:frontends
  tasks:
  - name: print all available facts
    ansible.builtin.debug:
      var: ansible_facts

# Setup database tier

- name: setup database tier
  become: yes
  hosts: appdbs
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: db-tier, tags: [dbs, postgres]}

- name: gather fact for apps and load-balancers
  hosts: apps:frontends 
  tasks:
  - name: print all available facts
    ansible.builtin.debug:
      var: ansible_facts

# Setup application servers tier

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}

# Setup front-end load balancer tier

- name: setup load-balancer tier
  hosts: frontends
  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lbs, haproxy]}

